### PR TITLE
[MIG] website_sale_cancel_quotations: Migration to 18.0

### PR DESCRIPTION
**Pull request by JrAdhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/331).

**Comment by lav-adhoc** [comment]
@roboadhoc r+

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @matiasperalta1: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
