### PR TITLE
[ADD] website_sale_hide_all_prices

### PR DESCRIPTION
**Pull request by cem-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/316).

**Comment by matiasperalta1** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by matiasperalta1** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
I'm sorry, @matiasperalta1: this PR is already reviewed, reviewing it again is useless.

**Pull request closed without merging**
