### PR TITLE
[FW][REF] website_sale_search_improved: change string

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/website#292

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/297).

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @Bruno-Zanotti cherrypicking of pull request ingadhoc/website#292 failed.

* 28da1f8c6eae6bf26409ee0d1e1555a664a71209 <- on this commit
* c02ebf85254e5860bd4ba957ee4910f47abe1f67

stdout:
```
Auto-merging website_sale_search_improved/views/res_config_settings_views.xml
CONFLICT (content): Merge conflict in website_sale_search_improved/views/res_config_settings_views.xml
Auto-merging website_sale_search_improved/__manifest__.py
CONFLICT (content): Merge conflict in website_sale_search_improved/__manifest__.py

```

stderr:
```
20:50:25.718538 git.c:444               trace: built-in: git cherry-pick 28da1f8c6eae6bf26409ee0d1e1555a664a71209
error: could not apply 28da1f8... [REF] website_sale_search_improved: change string
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@matiasperalta1 @Bruno-Zanotti unable to stage: All commits must have author and committer email, missing email on 077c8b0ce3a28590832806e789f90c9ecc6b2afb indicates the authorship is most likely incorrect.

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by matiasperalta1** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@matiasperalta1 @Bruno-Zanotti unable to stage: All commits must have author and committer email, missing email on c896a1fae22246821f868ba6ad3463f3bd6dba89 indicates the authorship is most likely incorrect.

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Pull request closed without merging**
