### PR TITLE
[FW][FIX] website_sale_order_type_ux: add stock warehouse in the public g…

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
…roup permissions

Forward-Port-Of: ingadhoc/website#270

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/273).

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
