### PR TITLE
[REF] website_sale_ux: translation corrected

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/326).

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#328

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#328

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#328

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#328

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#328

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#328

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#328

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#328

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#328

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#328

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#328

**Pull request closed without merging**
