### PR TITLE
[MIG] l10n_ar_website_sale_ux/: Migration to 16.0

### PR DESCRIPTION
**Pull request by jok-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/website/pull/235).

**Comment by JrAdhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@JrAdhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/235).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Pull request closed without merging**
