### PR TITLE
[MIG] website_sale_search_improved: Migration to 13.0

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/170).

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/runbot-oba rebase-ff

**Comment by jjscarafia** [comment]
@roboadhoc r-

**Comment by roboadhoc** [comment]
@jjscarafia you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia: you are not allowed to override this status.

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jjscarafia you may want to rebuild or fix this PR as it has failed CI.

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia: you are not allowed to override this status.

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia: you are not allowed to override this status.

**Pull request closed without merging**
