### PR TITLE
[MIG] website_sale_search_improved: Migration to 16.0

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/286).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by matiasperalta1** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#291

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#291

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#291

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#291

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#291

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#291

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#291

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#291

**Pull request closed without merging**
