### PR TITLE
[FW][FIX] website_sale_search_improved: fixing web tour bug

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/website#320

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/327).

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @lef-adhoc this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @lef-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
