### PR TITLE
[FW][MIG] google_tag_manager_advanced_tracking: Migration to 17.0

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/website#310

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/323).

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @JrAdhoc this PR targets 18.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @JrAdhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by JrAdhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @JrAdhoc this PR was closed then reopened. It should be merged the normal way (via @roboadhoc)

**Pull request merged**
