### PR TITLE
[MIG] l10n_ar_website_sale_ux: Migration to 15.0

### PR DESCRIPTION
**Pull request by JrAdhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/website/pull/210).

**Review by PabloPaezSheridan — DISMISSED** [review]

**Comment by PabloPaezSheridan** [comment]
r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
