### PR TITLE
[FIX] website_sale_search_improved: fixing web tour bug

### PR DESCRIPTION
**Pull request by cem-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/320).

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#327

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#327

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#327

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#327

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#327

**Comment by fw-bot-adhoc** [comment]
@cem-adhoc @lef-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#327

**Pull request closed without merging**
