### PR TITLE
[MIG] website_sale_prod_description: Migration to 16.0

### PR DESCRIPTION
**Pull request by jok-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/website/pull/237).

**Review by maq-adhoc — DISMISSED** [review]

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @maq-adhoc. I'm afraid I can't do that.

**Comment by JrAdhoc** [comment]
@roboadhoc r+

**Review by JrAdhoc — APPROVED** [review]

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request merged**
