### PR TITLE
[IMP] website_sale_ux: the name of the "pay now" button is changed

### PR DESCRIPTION
**Pull request by lef-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/274).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#276

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#276

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#276

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#276

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#276

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#276

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#276

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#276

**Pull request closed without merging**
