### PR TITLE
[REF] website_sale_search_improved: change string

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/292).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#297

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#297

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#297

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#297

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#297

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#297

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#297

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#297

**Pull request closed without merging**
