### PR TITLE
[FW][MIG] website_sale_search_improved: Migration to 16.0

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/website#286

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/291).

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @matiasperalta1 this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @matiasperalta1 ci/runbot-oba failed on this forward-port PR

**Comment by matiasperalta1** [comment]
@fw-bot-adhoc r+

**Comment by roboadhoc** [comment]
@matiasperalta1 you may want to rebuild or fix this PR as it has failed CI.

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @matiasperalta1 this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Pull request closed without merging**
