### PR TITLE
[FW][ADD]google_tag_manager_advanced_tracking: new module

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/website#256

### CODE REVIEW

**Comment by maq-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/259).

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by maq-adhoc** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by matiasperalta1** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Pull request closed without merging**
