### PR TITLE
[FIX] website_sale_order_type_ux: add stock warehouse in the public g…

### PR DESCRIPTION
**Pull request by lef-adhoc**
…roup permissions

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/270).

**Comment by matiasperalta1** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#273

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#273

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#273

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#273

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#273

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#273

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#273

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#273

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#273

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#273

**Comment by fw-bot-adhoc** [comment]
@matiasperalta1 this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#273

**Pull request closed without merging**
