### PR TITLE
[ADD]google_tag_manager_advanced_tracking: new module

### PR DESCRIPTION
**Pull request by JrAdhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/256).

**Review by maq-adhoc — APPROVED** [review]

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Comment by fw-bot-adhoc** [comment]
@JrAdhoc @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/website#259

**Pull request closed without merging**
