### PR TITLE
[FW][MIG] website_sale_search_improved: Migration to 13.0

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/website#170

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/242).

**Comment by fw-bot-adhoc** [comment]
This PR targets 15.0 and is part of the forward-port chain. Further PRs will be created up to 16.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@roboadhoc r+ rebase-ff

**Comment by fw-bot-adhoc** [comment]
@jjscarafia this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
