### PR TITLE
[FW][IMP] website_sale_order_validity: add update cart button in /shop/cart

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/website#289

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/290).

**Comment by fw-bot-adhoc** [comment]
@lef-adhoc @lav-adhoc cherrypicking of pull request ingadhoc/website#289 failed.

stdout:
```
Auto-merging website_sale_order_validity/views/templates.xml
Auto-merging website_sale_order_validity/i18n/es_AR.po
CONFLICT (content): Merge conflict in website_sale_order_validity/i18n/es_AR.po
Auto-merging website_sale_order_validity/__manifest__.py
CONFLICT (content): Merge conflict in website_sale_order_validity/__manifest__.py

```

stderr:
```
14:45:59.058620 git.c:444               trace: built-in: git cherry-pick ae7f71a7d03556059efc9623ab55ecb7f945ea9f
error: could not apply ae7f71a... [IMP] website_sale_order_validity: add update cart button in /shop/cart
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by lav-adhoc** [comment]
@lef-adhoc fran el FW no lo pude mezclar porque hay que revisar algunas cosas, miralo y cualquier cosa avisame

**Comment by lef-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
