### PR TITLE
[MIG] l10n_ar_website_sale_ux: Migration to 18.0

### PR DESCRIPTION
**Pull request by ALopez-Adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/346).

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-oba
@roboadhoc override=ci/runbot-modified-modules
@roboadhoc r+

**Comment by roboadhoc** [comment]
@zaoral you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral:
- you are not allowed to override this status.
- you are not allowed to override this status.

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-oba
@roboadhoc override=ci/runbot-modified-modules

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you are not allowed to override this status.

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-modified-modules

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral: you are not allowed to override this status.

**Comment by zaoral** [comment]
@roboadhoc override=ci/runbot-modified-modules

**Comment by zaoral** [comment]
@roboadhoc r+

**Pull request closed without merging**
