### PR TITLE
[MIG] website_sale_ux: Migration to 15.0

### PR DESCRIPTION
**Pull request by JrAdhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/website/pull/207).

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
