### PR TITLE
Change __manifest__

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/website/pull/250).

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Review by dib-adhoc — APPROVED** [review]

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @maq-adhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request merged**
